<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update Reviewbox Setting - param</name>
   <tag></tag>
   <elementGuidId>e9aebd71-aaa1-4237-bccd-2710e85e6fea</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;setting\&quot;: {\n    \&quot;accessory_text_font_size\&quot;: ${accessory_text_font_size},\n    \&quot;ask_a_question_mode\&quot;: \&quot;new_section\&quot;,\n    \&quot;auto_play_speed\&quot;: 5,\n    \&quot;body_text_font_size\&quot;: 14,\n    \&quot;border_radius\&quot;: 6,\n    \&quot;box_shadow\&quot;: \&quot;none\&quot;,\n    \&quot;button_background\&quot;: \&quot;rgba(40,41,61,1)\&quot;,\n    \&quot;button_outline_color\&quot;: \&quot;rgba(228,228,235,1)\&quot;,\n    \&quot;button_text_color\&quot;: \&quot;rgba(255,255,255,1)\&quot;,\n    \&quot;card_background_color\&quot;: \&quot;rgba(255,255,255,1)\&quot;,\n    \&quot;card_border_color\&quot;: \&quot;rgba(228,228,235,1)\&quot;,\n    \&quot;columns_on_mobile\&quot;: 1,\n    \&quot;custom_css\&quot;: null,\n    \&quot;customer_avatar\&quot;: \&quot;auto\&quot;,\n    \&quot;customer_name_format\&quot;: \&quot;full_name\&quot;,\n    \&quot;date_format\&quot;: \&quot;ll\&quot;,\n    \&quot;default_questions_sorting\&quot;: \&quot;newest_first\&quot;,\n    \&quot;default_reviews_sorting\&quot;: \&quot;by_date\&quot;,\n    \&quot;enable_auto_play\&quot;: true,\n    \&quot;enable_infinite_loop\&quot;: true,\n    \&quot;font_family\&quot;: \&quot;${font_family}\&quot;,\n    \&quot;font_size\&quot;: 14,\n    \&quot;heading_text_font_size\&quot;: 26,\n    \&quot;hide_for_products_without_reviews\&quot;: false,\n    \&quot;layout\&quot;: \&quot;grid\&quot;,\n    \&quot;links_color\&quot;: \&quot;rgba(40,41,61,1)\&quot;,\n    \&quot;margin_bottom\&quot;: 20,\n    \&quot;margin_top\&quot;: 20,\n    \&quot;max_width\&quot;: 1200,\n    \&quot;number_of_reviews_slider\&quot;: 8,\n    \&quot;primary_text_color\&quot;: \&quot;rgba(40,41,61,1)\&quot;,\n    \&quot;qna_customer_name_format\&quot;: \&quot;full_name\&quot;,\n    \&quot;qna_date_format\&quot;: \&quot;ll\&quot;,\n    \&quot;qna_show_customer_country_flag\&quot;: true,\n    \&quot;qna_show_positive_reactions_only\&quot;: false,\n    \&quot;qna_show_published_date\&quot;: true,\n    \&quot;qna_show_reaction_icon\&quot;: true,\n    \&quot;rating_icon_border_color\&quot;: \&quot;rgba(255,122,0,1)\&quot;,\n    \&quot;rating_icon_empty_color\&quot;: \&quot;rgba(204,204,204,1)\&quot;,\n    \&quot;rating_icon_filled_color\&quot;: \&quot;rgba(250,173,20,1)\&quot;,\n    \&quot;rating_icon_shape\&quot;: \&quot;default\&quot;,\n    \&quot;rating_icon_size\&quot;: 14,\n    \&quot;rating_icon_spacing\&quot;: 2,\n    \&quot;reviews_per_loading_grid\&quot;: 12,\n    \&quot;reviews_per_loading_list\&quot;: 5,\n    \&quot;secondary_text_color\&quot;: \&quot;rgba(143,144,166,1)\&quot;,\n    \&quot;section_background\&quot;: \&quot;rgba(255,255,255,1)\&quot;,\n    \&quot;show_average_rating\&quot;: true,\n    \&quot;show_card_border\&quot;: true,\n    \&quot;show_cta_buttons\&quot;: true,\n    \&quot;show_custom_questions_rating\&quot;: true,\n    \&quot;show_filter\&quot;: true,\n    \&quot;show_media_section\&quot;: false,\n    \&quot;show_positive_reactions_only\&quot;: false,\n    \&quot;show_published_date\&quot;: true,\n    \&quot;show_qna_section\&quot;: true,\n    \&quot;show_questions_search_box\&quot;: true,\n    \&quot;show_questions_sorting\&quot;: true,\n    \&quot;show_rating_distribution\&quot;: true,\n    \&quot;show_rating_icon_border\&quot;: false,\n    \&quot;show_reaction_icon\&quot;: true,\n    \&quot;show_review_media\&quot;: true,\n    \&quot;show_review_star\&quot;: true,\n    \&quot;show_reviewer_country_flag\&quot;: true,\n    \&quot;show_search_box\&quot;: true,\n    \&quot;show_sorting\&quot;: true,\n    \&quot;show_summary_section\&quot;: true,\n    \&quot;show_tabs\&quot;: true,\n    \&quot;show_title\&quot;: true,\n    \&quot;show_verified_badge\&quot;: true,\n    \&quot;slide_behavior\&quot;: \&quot;one_item\&quot;,\n    \&quot;verified_badge_color\&quot;: \&quot;rgba(6,136,80,1)\&quot;,\n    \&quot;write_a_review_mode\&quot;: \&quot;new_section\&quot;,\n    \&quot;your_brand_color\&quot;: \&quot;rgba(33,33,33,1)\&quot;\n  },\n  \&quot;contents\&quot;: [\n    {\n      \&quot;language_code\&quot;: \&quot;en\&quot;,\n      \&quot;content\&quot;: {\n        \&quot;summary_section_title\&quot;: \&quot;Customer Reviews hy\&quot;,\n        \&quot;summary_review_singular_format\&quot;: \&quot;[review_number] review hy\&quot;,\n        \&quot;summary_review_plural_format\&quot;: \&quot;[review_number] reviews\&quot;,\n        \&quot;summary_review_submit_label\&quot;: \&quot;Write A Review\&quot;,\n        \&quot;summary_qna_submit_label\&quot;: \&quot;Ask A Question\&quot;,\n        \&quot;summary_discount_amount\&quot;: \&quot;Get discount [discount_amount]\&quot;,\n        \&quot;review_empty_title\&quot;: \&quot;There are no customer reviews yet\&quot;,\n        \&quot;review_empty_content\&quot;: \&quot;Be the first to share your thoughts with other customers.\&quot;,\n        \&quot;qna_empty_title\&quot;: \&quot;There are no questions yet\&quot;,\n        \&quot;qna_empty_content\&quot;: \&quot;Don’t hesitate to share your concerns with us.\&quot;,\n        \&quot;review_load_more\&quot;: \&quot;Load more\&quot;,\n        \&quot;review_count\&quot;: \&quot;Reviews ([reviews_count])\&quot;,\n        \&quot;qna_question_count\&quot;: \&quot;Questions ([questions_count])\&quot;,\n        \&quot;review_filter_by\&quot;: \&quot;Filter\&quot;,\n        \&quot;review_filter_clear\&quot;: \&quot;Clear\&quot;,\n        \&quot;review_sort_by_date\&quot;: \&quot;Sort by date\&quot;,\n        \&quot;review_sort_by_rating\&quot;: \&quot;Sort by rating\&quot;,\n        \&quot;review_sort_by_content\&quot;: \&quot;Sort by content\&quot;,\n        \&quot;qna_sort_by_date\&quot;: \&quot;Sort by date\&quot;,\n        \&quot;review_section_title\&quot;: \&quot;Write A Review\&quot;,\n        \&quot;review_rating_label\&quot;: \&quot;Rating\&quot;,\n        \&quot;review_rating_empty\&quot;: \&quot;Please give us your rating\&quot;,\n        \&quot;review_upload_label\&quot;: \&quot;Add Media\&quot;,\n        \&quot;review_upload_max_photo_size\&quot;: \&quot;Maximum upload photo size: 10MB\&quot;,\n        \&quot;review_upload_max_video_size\&quot;: \&quot;Maximum upload video size: 100MB\&quot;,\n        \&quot;review_upload_max_attachments\&quot;: \&quot;Maximum attachments: 5 items\&quot;,\n        \&quot;review_upload_incorrect_format\&quot;: \&quot;The file must be .jpg, .png, .gif, .mp4 or .mov\&quot;,\n        \&quot;review_content_label\&quot;: \&quot;Feedback\&quot;,\n        \&quot;review_content_placeholder\&quot;: \&quot;Share your thought about the product\&quot;,\n        \&quot;review_content_required\&quot;: \&quot;This field is required\&quot;,\n        \&quot;review_name_label\&quot;: \&quot;Name\&quot;,\n        \&quot;review_name_placeholder\&quot;: \&quot;Enter your name\&quot;,\n        \&quot;review_name_required\&quot;: \&quot;This field is required\&quot;,\n        \&quot;review_email_label\&quot;: \&quot;Email\&quot;,\n        \&quot;review_email_placeholder\&quot;: \&quot;Enter your mail\&quot;,\n        \&quot;review_email_invalid\&quot;: \&quot;Invalid email format\&quot;,\n        \&quot;review_email_required\&quot;: \&quot;This field is required\&quot;,\n        \&quot;review_submit_label\&quot;: \&quot;Submit Review\&quot;,\n        \&quot;review_cancel_label\&quot;: \&quot;Cancel\&quot;,\n        \&quot;review_discount_suggestion\&quot;: \&quot;Upload review with photos or videos to get [discount_amount] discount instantly!\&quot;,\n        \&quot;review_thank_you_title\&quot;: \&quot;Thank you!\&quot;,\n        \&quot;review_thank_you_content\&quot;: \&quot;Thank you for being one of our success stories!\&quot;,\n        \&quot;review_discount_content\&quot;: \&quot;Take your Discount [discount_amount] coupon now\&quot;,\n        \&quot;review_shop_now\&quot;: \&quot;Shop now\&quot;,\n        \&quot;review_discount_expiry_date\&quot;: \&quot;Expiry date: [expiry_date]\&quot;,\n        \&quot;qna_section_title\&quot;: \&quot;Write A Question\&quot;,\n        \&quot;qna_question_label\&quot;: \&quot;Question\&quot;,\n        \&quot;qna_question_placeholder\&quot;: \&quot;Write your question here\&quot;,\n        \&quot;qna_question_required\&quot;: \&quot;This field is required\&quot;,\n        \&quot;qna_name_label\&quot;: \&quot;Name\&quot;,\n        \&quot;qna_name_placeholder\&quot;: \&quot;Enter your name\&quot;,\n        \&quot;qna_name_required\&quot;: \&quot;This field is required\&quot;,\n        \&quot;qna_email_label\&quot;: \&quot;Email\&quot;,\n        \&quot;qna_email_placeholder\&quot;: \&quot;Enter your mail\&quot;,\n        \&quot;qna_email_invalid\&quot;: \&quot;Invalid email format\&quot;,\n        \&quot;qna_email_required\&quot;: \&quot;This field is required\&quot;,\n        \&quot;qna_submit_label\&quot;: \&quot;Submit Question\&quot;,\n        \&quot;qna_cancel_label\&quot;: \&quot;Cancel\&quot;,\n        \&quot;qna_thank_you_title\&quot;: \&quot;Thank you!\&quot;,\n        \&quot;qna_thank_you_content\&quot;: \&quot;Thank you for being one of our success stories!\&quot;,\n        \&quot;review_sort_by_media\&quot;: \&quot;Sort by media\&quot;,\n        \&quot;qna_sort_by_date_newest\&quot;: \&quot;Newest first\&quot;,\n        \&quot;qna_sort_by_date_oldest\&quot;: \&quot;Oldest first\&quot;,\n        \&quot;qna_load_more\&quot;: \&quot;Load more\&quot;,\n        \&quot;qna_search_box_placeholder\&quot;: \&quot;Search for questions\&quot;,\n        \&quot;qna_see_more\&quot;: \&quot;See more\&quot;,\n        \&quot;qna_helpful\&quot;: \&quot;Was this helpful?\&quot;,\n        \&quot;review_search_box_placeholder\&quot;: \&quot;Search for reviews\&quot;,\n        \&quot;review_see_more\&quot;: \&quot;See more\&quot;,\n        \&quot;review_verified_purchase\&quot;: \&quot;Verified purchase\&quot;,\n        \&quot;review_not_verified_purchase\&quot;: \&quot;Rating\&quot;,\n        \&quot;review_helpful\&quot;: \&quot;Was this helpful?\&quot;,\n        \&quot;review_empty\&quot;: \&quot;There are no customer reviews yet.\&quot;,\n        \&quot;custom_question_required\&quot;: \&quot;This field is required\&quot;,\n        \&quot;media_gallery_title\&quot;: \&quot;All media\&quot;\n      }\n    }\n  ]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>3c377994-d752-4fc6-b428-8f6c770f0693</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authorization</name>
      <type>Main</type>
      <value>${authorization}</value>
      <webElementGuid>e2038697-f7b4-4286-b98e-bdb935c97467</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.1.0</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${GlobalVariable.base_url_new_widget}/api/widgets/review_box</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkZXN0IjoiaHR0cHM6XC9cL2h1eW5oLWFyLW5ld3dpZGdldC1zdGFnLWRhaWx5LTEwMDIubXlzaG9waWZ5LmNvbSIsImlhdCI6MTcwMzQ3ODQ4NiwiZXhwIjoxNzAzNDgyMDg2fQ.cVGqQLVdQumf85kR4bDWDTMpoqrxQ_YCPbg3amrlAN4'</defaultValue>
      <description></description>
      <id>59d1be86-72f2-4da8-a74c-dc57161c6c52</id>
      <masked>false</masked>
      <name>authorization</name>
   </variables>
   <variables>
      <defaultValue>12</defaultValue>
      <description></description>
      <id>e8ed8bb2-8efb-4097-9070-06ff7a8ced9a</id>
      <masked>false</masked>
      <name>accessory_text_font_size</name>
   </variables>
   <variables>
      <defaultValue>'new_section'</defaultValue>
      <description></description>
      <id>39be4678-a898-473a-b678-19a415f44643</id>
      <masked>false</masked>
      <name>ask_a_question_mode</name>
   </variables>
   <variables>
      <defaultValue>5</defaultValue>
      <description></description>
      <id>0db4178b-1c51-4392-b098-4d1914d30354</id>
      <masked>false</masked>
      <name>auto_play_speed</name>
   </variables>
   <variables>
      <defaultValue>14</defaultValue>
      <description></description>
      <id>7c7fda2f-75fb-4318-b4d8-2ee8290063e5</id>
      <masked>false</masked>
      <name>body_text_font_size</name>
   </variables>
   <variables>
      <defaultValue>6</defaultValue>
      <description></description>
      <id>9835598e-5b43-4532-adf3-bd6e86f5bdc6</id>
      <masked>false</masked>
      <name>border_radius</name>
   </variables>
   <variables>
      <defaultValue>'none'</defaultValue>
      <description></description>
      <id>4ea9793f-bb00-4dda-bfcc-4bd801e8bed1</id>
      <masked>false</masked>
      <name>box_shadow</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>329d2245-f7e8-4fa5-b124-9ebaabd52892</id>
      <masked>false</masked>
      <name>button_background</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d08df4f6-b1bd-4b14-b933-2ce83b0f1429</id>
      <masked>false</masked>
      <name>button_outline_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0319861a-5bb4-461a-a23d-9381084c7eaf</id>
      <masked>false</masked>
      <name>button_text_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8235ad15-69e6-42af-bc0d-fd126a5a6920</id>
      <masked>false</masked>
      <name>card_background_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6c699247-04b1-463f-bd8c-9345e687f1c9</id>
      <masked>false</masked>
      <name>card_border_color</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>c35029e7-8dfd-46a9-a9a1-49aff25f1bba</id>
      <masked>false</masked>
      <name>columns_on_mobile</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0adb5936-47e6-4367-bff8-4ab077539d16</id>
      <masked>false</masked>
      <name>custom_css</name>
   </variables>
   <variables>
      <defaultValue>'auto'</defaultValue>
      <description></description>
      <id>b5749907-de95-44ac-899f-fbdb34d9f942</id>
      <masked>false</masked>
      <name>customer_avatar</name>
   </variables>
   <variables>
      <defaultValue>'full_name'</defaultValue>
      <description></description>
      <id>2e467719-82a6-4e96-92f3-f8c52241afeb</id>
      <masked>false</masked>
      <name>customer_name_format</name>
   </variables>
   <variables>
      <defaultValue>'ll'</defaultValue>
      <description></description>
      <id>499ec012-571d-4e31-a030-afd3e229f8a7</id>
      <masked>false</masked>
      <name>date_format</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>03430d16-d762-449c-87ea-4a11d5990b82</id>
      <masked>false</masked>
      <name>default_questions_sorting</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8796e3bd-9e51-42a8-89a9-5b532a12f58c</id>
      <masked>false</masked>
      <name>default_reviews_sorting</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5fa11f32-91ce-44a8-a681-411179f03b10</id>
      <masked>false</masked>
      <name>enable_auto_play</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4ac30b34-2a3a-476f-be05-5a85d8021d75</id>
      <masked>false</masked>
      <name>enable_infinite_loop</name>
   </variables>
   <variables>
      <defaultValue>'inherit'</defaultValue>
      <description></description>
      <id>65b54ad9-557f-4198-aa41-f9c7e835cada</id>
      <masked>false</masked>
      <name>font_family</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>f02b21a3-c834-44e4-ba04-4372c92667d1</id>
      <masked>false</masked>
      <name>font_size</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>10434bfa-9201-4339-8f74-ada9942814e2</id>
      <masked>false</masked>
      <name>heading_text_font_size</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>9125ef32-cfa9-4688-9b1a-36a134a8bbea</id>
      <masked>false</masked>
      <name>hide_for_products_without_reviews</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4e52b193-dfb1-4666-8be3-34ba5e4ade27</id>
      <masked>false</masked>
      <name>layout</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>9e28ff29-e0bf-445d-be7e-8ff0789b7bc1</id>
      <masked>false</masked>
      <name>margin_bottom</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>9d7c67e0-7e24-4452-bb63-b09ab65cd50e</id>
      <masked>false</masked>
      <name>margin_top</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>348f243c-72d0-4692-b83c-ad5272183360</id>
      <masked>false</masked>
      <name>max_width</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>57eb3071-2c14-4fc4-8026-e5ed57b46a65</id>
      <masked>false</masked>
      <name>number_of_reviews_slider</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3ee26084-6b86-46ed-bc0b-441754b06229</id>
      <masked>false</masked>
      <name>primary_text_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e0b20655-5cd1-4cb1-82d0-86449f122a2c</id>
      <masked>false</masked>
      <name>qna_customer_name_format</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9759cf1d-4a94-48ea-809f-6a49f7fb4941</id>
      <masked>false</masked>
      <name>qna_date_format</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>506b66ed-4af8-4503-8439-3288d8d71cb8</id>
      <masked>false</masked>
      <name>qna_show_customer_country_flag</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>fa0accad-7fa7-46da-85f0-38eada095d03</id>
      <masked>false</masked>
      <name>qna_show_positive_reactions_only</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>bf08320f-d7ee-41b1-a0bd-c11efc3b9674</id>
      <masked>false</masked>
      <name>qna_show_published_date</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>5a162822-775a-4ace-9d00-8bf81e9b413f</id>
      <masked>false</masked>
      <name>qna_show_reaction_icon</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d8e4ba21-83f9-473a-8d75-76b60f3c7a2e</id>
      <masked>false</masked>
      <name>rating_icon_border_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>deedc3aa-2022-42c9-9756-3d77f4f172c3</id>
      <masked>false</masked>
      <name>rating_icon_empty_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fc936ef7-4698-4cd0-a6dd-49bcc8949625</id>
      <masked>false</masked>
      <name>rating_icon_filled_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>aae7bcf0-1703-441c-a3e0-85da8c0f5e09</id>
      <masked>false</masked>
      <name>rating_icon_shape</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>1be88002-729a-4f90-8479-73008ecc9863</id>
      <masked>false</masked>
      <name>rating_icon_size</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>fd1ba4c6-9099-43f1-b02c-1051d62b647d</id>
      <masked>false</masked>
      <name>rating_icon_spacing</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>ace99bfe-ca94-4af3-845a-8a6a6ecf05d7</id>
      <masked>false</masked>
      <name>reviews_per_loading_grid</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>b0a42c6f-1d58-4357-b0fd-c7a883ca7046</id>
      <masked>false</masked>
      <name>reviews_per_loading_list</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b321a88c-5e6f-4946-9190-5ef317f879b9</id>
      <masked>false</masked>
      <name>secondary_text_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e7809b7e-bf9f-45b6-8ece-9da97757d4d2</id>
      <masked>false</masked>
      <name>section_background</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>76153f5a-de70-4dea-9ffe-60c163bcec1a</id>
      <masked>false</masked>
      <name>show_average_rating</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>deb5284b-fae6-4e20-a5ae-f76c7c8def9f</id>
      <masked>false</masked>
      <name>show_card_border</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>a2ad71c1-88bf-4e63-89b5-482ddd982eb1</id>
      <masked>false</masked>
      <name>show_cta_buttons</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>fb6be24d-760d-4509-94ad-067b596ac616</id>
      <masked>false</masked>
      <name>show_custom_questions_rating</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>d388cbea-2cdf-4e13-9b82-f00c501d1193</id>
      <masked>false</masked>
      <name>show_filter</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>2cf0f65c-01ad-4336-8cf5-08fdd232ce03</id>
      <masked>false</masked>
      <name>show_media_section</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>e94219cb-5e67-4427-91a5-c28e7bc29417</id>
      <masked>false</masked>
      <name>show_positive_reactions_only</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>e27254c6-732a-46c1-89c8-71af9aa83f8f</id>
      <masked>false</masked>
      <name>show_published_date</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>9b824dac-e3a9-4beb-9375-31e83f3b92bb</id>
      <masked>false</masked>
      <name>show_qna_section</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>cdeddb8c-6a15-43d9-abf2-621699bc6f54</id>
      <masked>false</masked>
      <name>show_questions_search_box</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>3d6bf5a3-42f5-46d3-ba1a-0bbf92054fcf</id>
      <masked>false</masked>
      <name>show_questions_sorting</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>642a08fb-467b-4ce2-8be8-8ee76b624f61</id>
      <masked>false</masked>
      <name>show_rating_distribution</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>8500b6bb-e9d9-4be5-965e-cb2c386c5519</id>
      <masked>false</masked>
      <name>show_rating_icon_border</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>b37ff127-9dd0-4506-af21-eceb0d6283c1</id>
      <masked>false</masked>
      <name>show_reaction_icon</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>e1348e25-6eeb-4b16-a1c8-ed52ae263292</id>
      <masked>false</masked>
      <name>show_review_media</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>12718a6a-0471-4a56-999f-a0605c3696a7</id>
      <masked>false</masked>
      <name>show_review_star</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>d575a03a-8cc1-499f-82a6-d2dcc35cdcba</id>
      <masked>false</masked>
      <name>show_reviewer_country_flag</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>3331f917-b1e3-4d34-bf06-a6c81f275fe8</id>
      <masked>false</masked>
      <name>show_search_box</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>f5faaf09-0d85-4dee-baeb-cb3facaea7bc</id>
      <masked>false</masked>
      <name>show_sorting</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>ed779649-d084-4132-b394-78111da56437</id>
      <masked>false</masked>
      <name>show_summary_section</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>f2877eac-3e34-4cf4-85fd-27257e6661dd</id>
      <masked>false</masked>
      <name>show_tabs</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>58fec505-bae5-439f-9270-41553cd79664</id>
      <masked>false</masked>
      <name>show_title</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>38ee40ac-01fa-4f2c-b752-5bb47958d3a5</id>
      <masked>false</masked>
      <name>show_verified_badge</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6dfd72a1-6a44-4c74-bfd7-a175ac88ff48</id>
      <masked>false</masked>
      <name>slide_behavior</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b0043650-c9d1-4b5c-9a2c-c91849c12009</id>
      <masked>false</masked>
      <name>verified_badge_color</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>77bd84b4-e659-407d-a25d-24c96299bfc4</id>
      <masked>false</masked>
      <name>write_a_review_mode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ea22cb7f-b1d2-4bec-a31f-90f1766bbfb2</id>
      <masked>false</masked>
      <name>your_brand_color</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()
</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
